// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa_lDQgrOjrHJGLVPfyYUcXgsYRa8AUEE',
    appId: '1:881312176002:web:d5b8a2b6677b3d9545219b',
    messagingSenderId: '881312176002',
    projectId: 'emploi-hunt',
    authDomain: 'emploi-hunt.firebaseapp.com',
    databaseURL: 'https://emploi-hunt-default-rtdb.firebaseio.com',
    storageBucket: 'emploi-hunt.appspot.com',
    measurementId: 'G-VGJKNCSW6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr0KdGDKP380cNUqQd00V8A7diax4RQJQ',
    appId: '1:881312176002:android:c36b9235567cc28545219b',
    messagingSenderId: '881312176002',
    projectId: 'emploi-hunt',
    databaseURL: 'https://emploi-hunt-default-rtdb.firebaseio.com',
    storageBucket: 'emploi-hunt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGSBl8JqAozIwrg2uDa1JchMooCQtLeoI',
    appId: '1:881312176002:ios:5385a6f842434a8545219b',
    messagingSenderId: '881312176002',
    projectId: 'emploi-hunt',
    databaseURL: 'https://emploi-hunt-default-rtdb.firebaseio.com',
    storageBucket: 'emploi-hunt.appspot.com',
    androidClientId: '881312176002-bs5laetreq5pshjqmnuoih8o77nh1d33.apps.googleusercontent.com',
    iosBundleId: 'com.amri.emploihunt',
  );
}
